"""
Package definitions for Manjaro Package Builder
"""

# LOCAL packages (from our repository)
LOCAL_PACKAGES = [
#    "capitaine-cursors-sainnhe-git",
#    "manjaro-live",
    "cuda-12.9",
    "cudnn9.10-cuda12.9",
    "capitaine-cursors-nord-git",
#    "lua54",
#    "lgi",
    "gghelper",
    "terminal-tutor",
    "gtkhash-thunar",
    "gtkhash-thunar-git",
    "gtkhash-nautilus-gtk4-git",
    "gtkhash-nemo-git",
    "gtkhash-caja-git",
    "stable-diffusion-webui-forge",
    "stable-diffusion-webui-forge-cu124",
    "stable-diffusion-webui-forge-neo-git",
    "picom-pijulius-next-git",
    "manjaro-awesome-keyring",
    "moneymanagerex",
    "nordic-theme-git",
    "nordic-polar-theme-git",
    "nordic-theme",
    "kohya_ss",
    "kohya_ss-cu124",
    "kohya_ss-cu126",
    "comfyui-git",
    "comfyui",
    "comfyui-cu126",
    "comfyui-cu126-git",
    "compiz-easy-patch",
    "compiz-easy-patch-git",
#    "stable-diffusion-webui-forge-sd35",
    "hyperfluent-grub-theme-manjaro",
    "dmgrub-nord-1080p",
    "dmgrub-nord-1080p-ai",
    "dmgrub-nord-1440p",
    "dmgrub-nord-1440p-ai",
    "manjaro-distro-grub-theme",
    "manjaro-gnome-settings",
    "manjaro-distro-grub-theme-ai",
    "gtk2",
    "awesome-freedesktop-git",
    "lain-git",
    "awesome-rofi",
    "awesome-git",
    "awesome54-git",
    "awesome-welcome",
    "awesome-welcome-ai",
    "tilix-git",
    "nordic-backgrounds",
    "awesome-copycats-manjaro",
    "i3lock-fancy-git",
    "ttf-font-awesome-5",
    "tamzen-font",
    "nvidia-driver-assistant",
    "xlibre-keyring",
    "grayjay-bin"
]

# AUR packages (from Arch User Repository)
AUR_PACKAGES = [
    "libinput-gestures",
#    "picom-pijulius-next-git",
    "gtkd",
    "qt5-styleplugins",
    "papirus-folders-nordic",
    "urxvt-resize-font-git",
    "i3lock-color",
    "raw-thumbnailer",
    "gsconnect",
    "gnome-shell-extension-nightthemeswitcher",
    "betterlockscreen",
#    "nordic-theme",
    "geany-nord-theme",
    "nordzy-icon-theme",
    "oh-my-posh-bin",
    "fish-done",
    "find-the-command",
    "p7zip-gui",
    "python310",
    "python313",
    "qownnotes",
    "xorg-font-utils",
    "xnviewmp",
    "simplescreenrecorder",
#    "gtkhash-thunar",
    "a4tech-bloody-driver-git"
]

# Optionally, you can also define package groups or categories
PACKAGE_CATEGORIES = {
    "desktop": ["awesome-freedesktop-git", "lain-git", "awesome-rofi"],
    "themes": ["nordic-theme", "nordic-darker-theme", "nordic-bluish-accent-theme"],
    "fonts": ["tamzen-font", "ttf-font-awesome-5"],
    "tools": ["libinput-gestures", "betterlockscreen", "simplescreenrecorder"],
    "drivers": ["nvidia-driver-assistant", "a4tech-bloody-driver-git"]
}
